image: python:3.10

before_script:
  - pip install -r update/requirements.txt
  - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
  - eval `ssh-agent -s`
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - update

pages:
  stage: update
  script:
    - git config --global user.email "ine-bot@example.com"
    - git config --global user.name "ine-bot"
    - git remote set-url --push origin git@gitlab.com:mauforonda/ine.git
    - git remote show origin
    - git pull origin master
    - python update/AsyncUpdaterRetriesWorkers.py 
    - git status
    - git add -A
    - git commit -m "[skip ci] update"
    - git push --force origin HEAD:$CI_COMMIT_REF_NAME
    - ls -a
    - mkdir public
    - cp *.csv public/
  artifacts:
    paths:
      - public
  only:
    - master
