name: Update
on:
  schedule:
    - cron: '0 6 * * 3'
  workflow_dispatch:
jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: setup python and locale
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
          locale -a
          sudo locale-gen es_US.UTF-8
          sudo update-locale LANG=es_US.UTF-8
      - name: update catalogo
        run: |
          python3 update/update_data.py
        id: update_catalogo
      - name: update page
        run: |
          ./update/diff.sh > catalogo_diff.csv
          jupyter nbconvert --to notebook --inplace --execute index.ipynb
          ./update/publish.sh index.ipynb 
      - name: commit
        run: |
          git config --global user.email "ine-bot@example.com"
          git config --global user.name "ine-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] $(cat update_time)"; git push -q "https://$GH_TOKEN@github.com/mauforonda/catalogo-ine.git" master)
