name: Update
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: setup python
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: run update script
        run: |
          bash update/update.sh
      - name: git status
        id: git-status
        run: |
          git config --global user.email ine-bot@example.com"
          git config --global user.name ine-bot"
          echo ::set-output name=result::$(git diff catalogo_ine.csv | wc -l)
      - name: commit
        if: steps.git-status.outputs.result != 0
        run: |
          git add -A
          git commit -m "[ci] actualización"
          git push -q "https://$GH_TOKEN@github.com/mauforonda/catalogo-ine.git" master
